### ISSUE TITLE
[Q] OSX support

### ISSUE THREAD

**Issue by FL3SH** [kyazdani42/nvim-web-devicons#10]
Hi, how can I make it work with iterm2 on OSX?
I am using default iterm2 font - `Monaco`.

**Comment by akinsho** [comment]
@FL3SH I use this plugin on Mac and Linux and it works in both it sounds like you might not be using a patched font though which would probably render weirdly

**Comment by FL3SH** [comment]
Exactly, I was able to make it work by patching my `Monaco` font using [font-patcher](https://github.com/ryanoasis/nerd-fonts#font-patcher).
