### ISSUE TITLE
Change all icon colors

### ISSUE THREAD

**Issue by n1ghtmare** [kyazdani42/nvim-web-devicons#101]
Is it possible to change the colors of all icons somehow (without going through them one by one)?

**Comment by kyazdani42** [comment]
you could write a method to get the list of all highlight groups that start with DevIcon and mapping the color you want to them in a loop.

**Comment by kyazdani42** [comment]
or see https://github.com/kyazdani42/nvim-web-devicons/issues/102#issuecomment-998255906 
and adapt the code to only change the color of the icon

**Comment by n1ghtmare** [comment]
@kyazdani42 Thank you this is really helpful, will see what I can do.

**Comment by n1ghtmare** [comment]
In case someone is looking for this, here is what I did (thanks to @kyazdani42) that works just fine:

```lua
local nvim_web_devicons = require "nvim-web-devicons"

local current_icons = nvim_web_devicons.get_icons()
local new_icons = {}

for key, icon in pairs(current_icons) do
    icon.color = "#ff0088"
    icon.cterm_color = 198
    new_icons[key] = icon
end

nvim_web_devicons.set_icon(new_icons)
```

**Comment by n1ghtmare** [comment]
@kyazdani42 would you have an idea why when I go ahead and set the highlight group of a DevIcon doesn't appear to affect the icon colors of nvim-tree?

So I have a color scheme (.vim) and I'm trying to set the colors there (instead of hard coding this in my config).

If I call `:hi DevIconLua guifg=#ff0088` as a command it seems to be working, but when I set it in my theme it doesn't. (if I set `hi NvimTreeFolderIcon guifg=#ffffff` in my theme file for example, it works). Does it have something to do with the order of things being loaded? Are the values in my theme file being overwritten perhaps?

Sorry for the newbish questions. Thanks for helping out.

**Comment by kyazdani42** [comment]
I think it's a bug actually, nvim-web-devicons override predefined sets of colors when running the highlight while nvim-tree doesn't.
Can you try removing the exclamation mark at line 1260 in lua/nvim-web-devicons.lua and try again ? It might work. If so open a PR :)

**Comment by n1ghtmare** [comment]
@kyazdani42 I'm guessing you mean [line 1264](https://github.com/kyazdani42/nvim-web-devicons/blob/master/lua/nvim-web-devicons.lua#L1264), or more specifically:

```lua
local highlight_command = "highlight! "..hl_group
```

I've tried removing the exclamation mark, but unfortunately it didn't work. :(

**Comment by kyazdani42** [comment]
Could you open a new issue so we can track this properly please :) ?

**Comment by n1ghtmare** [comment]
@kyazdani42 I did, sorry for the late response, I meant to open this sooner, but it slipped my mind. :)
