### ISSUE TITLE
Option for disabling colors

### ISSUE THREAD

**Issue by macthecadillac** [kyazdani42/nvim-web-devicons#109]
Could you provide a setting to disable all colors? Thanks

**Comment by kyazdani42** [comment]
why would you want that ? We could implement if it makes sense

**Comment by macthecadillac** [comment]
I think having an option is always a good thing. Besides, I like it being
monochrome since the colors as they are don't necessarily fit with some
color schemes.

It would also be nice if you could provide variants of the default color
scheme that use the palette of some popular color schemes so people can opt
in to use those palettes and fall back to the default/monochrome schemes if
necessary.

**Comment by kyazdani42** [comment]
I believe colorscheme developers should take that into account. Given the colors are colors taken from original logos, i believe this is a good default, and if people don't like it somehow, they should just change it, as its configurable.
If you want to add a feature to disable the colors, go for it, but you could do it programmatically and i think it's not something that would be needed by most people, so i'd prefer if it doesn't go in the plugin which should stay as simple as possible.

**Comment by ioreshnikov** [comment]
> I believe colorscheme developers should take that into account.

The current implementation makes it difficult. I am trying to implement my own theme at the moment. I am using [lush](https://github.com/rktjmp/lush.nvim) as a framework since it allows you to apply the highlight colors in runtime without reloading the theme. So when I edit `DevIcon*` highlight groups, I can see that the colors are indeed set. However, everything is gone when I actually try to load the theme.

The problem is that there's an unconditional call to `set_up_highlight()` that is set as an autocmd on color scheme change that simply overrides everything. 

So theming is not really easy.

**Comment by gma** [comment]
I'd really appreciate being able to disable all the custom icon colours. It looks pretty bad with my colour scheme (gruvbox, with Vim and my terminal configured with the base16 shell themes).

You asked "why would you want that ?" My simple answer is "I'd prefer it". Stuff like this is subjective.

A longer answer involves explaining that it really doesn't look good to me with gruvbox, and I've no idea how to disable it myself.

I'm sure someone with more experience could write custom code to do it, but I expect it would take me six hours of digging into stuff that I'm not particularly interested in (I don't code Lua, don't write color schemes for Vim, don't really understand how these icon fonts work, etc). So I'd have a lot to learn and wouldn't see enough benefit for the time I'd have to invest.

To give you a bit more context, I'm afraid I just don't understand this paragraph (from the README) at all:

> This adds all the highlight groups for the devicons i.e. it calls highlight IconNameDevicon guifg='<color>' ctermfg='<cterm_color>' for all icons this might need to be re-called in a Colorscheme to re-apply cleared highlights if the color scheme changes

What's a highlight group? `IconNameDevicon` - is that a keyword or a placeholder for a name? Where do `guifg` and `ctermfg` come from? There are so many concepts wrapped up in this paragraph that I'm not keen on learning about right now. But if I could just disable coloured icons with a setting, I'd do that and be on my way. I think the README could do with some examples with real values filled in.

I hope this is a useful comment. I'm about to revert the addition of this plugin to my config and delete the nerdfonts from my `~/.fonts` folder, but will have another go if the opportunity to set a single colour for all the icons turns up...
