### ISSUE TITLE
Devicons in lualine statusbar plugin

### ISSUE THREAD

**Issue by mustafaergul** [kyazdani42/nvim-web-devicons#111]
I am currently using `nvim-web-devicons` with `nonicons` as well. However `nonicons` is not functional on `lualine` plugin. While the term is set to `nonicons` can I still be able to use the `nvim-web-devicons` on the status bar?

![image](https://user-images.githubusercontent.com/5095547/154307111-72ca2b69-f329-4a07-87fa-a4136de67de0.png)

**Comment by kyazdani42** [comment]
do you mean you wish to use a different icon set in nvim-web-devicons for lualine ? It's not possible immediately in the plugin, although you could hack around a solution yourself, by setting icons on bufenter or something like that i guess. Not sure it would work though.

**Comment by mustafaergul** [comment]
Thank you for the additional workaround suggestion.
