### ISSUE TITLE
Changing the highlight group of a `DevIcon` doesn't affect the icon colors of `nvim-tree`

### ISSUE THREAD

**Issue by n1ghtmare** [kyazdani42/nvim-web-devicons#112]
I have a color scheme (.vim) and I'm trying to set the colors there (instead of hard coding this in my config).

If I call `:hi DevIconLua guifg=#ff0088` as a command it seems to be working fine. However, when I set it in my theme file it doesn't.  For comparison when I set `hi NvimTreeFolderIcon guifg=#ffffff` in my theme file for example, it works.

NOTE: This is in reference to https://github.com/kyazdani42/nvim-web-devicons/issues/101#issuecomment-998319192

**Comment by kyazdani42** [comment]
Hi :)
1st could you try adding an exclamation mark to your highlight in your colorscheme to see if it changes something ? I don't think it'll resolve this if the colorscheme applies before nvim-web-devicons sets it's colors on colorscheme change though.

**Comment by kyazdani42** [comment]
Hum forget it, just tried it, the highlight gets overriden by nvim-web-devicons.

**Comment by kyazdani42** [comment]
should be working now, i made a hack around this for now
