### ISSUE TITLE
set_icon work but setup not work

### ISSUE THREAD

**Issue by tin-pham** [kyazdani42/nvim-web-devicons#121]
![image](https://user-images.githubusercontent.com/20679090/161374695-5b16b4b8-2686-474d-aa31-2fc71020d088.png)

![image](https://user-images.githubusercontent.com/20679090/161374729-564701b0-1f04-439e-bfae-21c27016c232.png)

Even i remove the set_icon 
![image](https://user-images.githubusercontent.com/20679090/161374773-a4d07cba-c084-4266-b07a-9ac8560977f8.png)

**Comment by kyazdani42** [comment]
I think this might be expected since setup can be only called once.
You can check `nvim-web-devicons.has_loaded()` to see if you can call setup.
Plugins might call setup before you do.

**Comment by tin-pham** [comment]
![image](https://user-images.githubusercontent.com/20679090/161383262-1f0967d7-a78e-431a-9e55-026c0fa418f4.png)
How can i run has_loaded() function (sorry i kinda new to nvim)

**Comment by kyazdani42** [comment]
set_icon doesn't care if the plugin is loaded or not.
but you could do:
```lua
if not web_devicons.has_loaded() then
  web_devicons.setup { }
end
```

**Comment by tin-pham** [comment]
It still not work
![image](https://user-images.githubusercontent.com/20679090/161415603-189b4764-b55b-41f6-99de-eb731f1df476.png)

set_icons work just fine, but i want to add filetype like this, but it not work in set_icons, so i try setup and discover it was not work
![image](https://user-images.githubusercontent.com/20679090/161415645-226e019b-9e72-4b60-9cbb-3fd0bea89ecf.png)

![image](https://user-images.githubusercontent.com/20679090/161415685-35780e78-d515-4a47-a5a0-19eb735890ca.png)

**Comment by kyazdani42** [comment]
1) if a plugin sets it before, it will not run. Check with a `print(1)` if it goes into it.
2) the name should not contain spaces as it will be passed in `:highlight`

**Comment by tin-pham** [comment]
![image](https://user-images.githubusercontent.com/20679090/161487731-d490bda9-53e4-47ab-a292-44ea063c5a2c.png)
Thanks for the 'space', I remove space and it worked
About the setup it still not work but anyway, set_icon work just fine
