### ISSUE TITLE
Icons doesn't show with JetBrains Mono font

### ISSUE THREAD

**Issue by xbladesub** [kyazdani42/nvim-web-devicons#134]
Icons not shown when I use JetBrains Mono font. (lunarvim/neovide). 
Nvim version:  0.7
macOS: 12.3.1

Any solutions?

<img width="621" alt="Screen Shot 2022-05-24 at 6 45 24 PM" src="https://user-images.githubusercontent.com/45129790/170017368-77b34806-fec8-44f8-a553-782ef84730d5.png">

**Comment by xbladesub** [comment]
had to restart my machine

**Comment by t1mursadykov** [comment]
Have the same problem

![image](https://user-images.githubusercontent.com/18900450/172058293-bfe2c366-d068-4e6e-a985-246366a0f2e1.png)

**Comment by xbladesub** [comment]
> Have the same problem
> 
> ![image](https://user-images.githubusercontent.com/18900450/172058293-bfe2c366-d068-4e6e-a985-246366a0f2e1.png)

make sure you are using nerd font (JebrainsMono NF or Fira Code NF for example)
