### ISSUE TITLE
Different icons and colors like vscode depending on filename

### ISSUE THREAD

**Issue by jugarpeupv** [kyazdani42/nvim-web-devicons#135]
Hi,

Thanks for this awesome plugin, is it possible to set different icons/colors depending on the ending of a filename? I am working with angular and vscode shows different icons and colors like so

<img width="690" alt="image" src="https://user-images.githubusercontent.com/69123204/170822240-00862d20-abdd-4c29-9461-73462084dd97.png">

**Comment by kyazdani42** [comment]
you can by setting it like this:
```lua
require "nvim-web-devicons".set_icon {
  "service.ts" = { icon = "A", color = "#00ffff", name = "AngularService" },
  "directive.ts" = " { icon = "A", color = "#00aaff", name = "AngularDirective" },
  // and so on and so on
}
```

**Comment by jugarpeupv** [comment]
Many thanks for the quick response!!

Now icons are rendering on nvim tree accordingly but not in telescope and bufferline, do you know how to apply to this plugins? I will check their docs, thanks anyways!

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/69123204/170862703-86166d95-b166-49a4-9573-7ea79987117d.png">

**Comment by kyazdani42** [comment]
Hum i believe it's because i've implemented a recursive check for filenames which makes this work. If other plugins pass in just the simple extension it will not work unfortunately.

**Comment by jugarpeupv** [comment]
I understand, many thanks anyway ^^

**Comment by jugarpeupv** [comment]
Hey kyaz, just a quick note regarding this matter. Just by setting "service.ts" i noticed a file called literally 'service.ts' is displayed with the correct icon in telescope

I was trying to set some wildcard to make it render with all .service.ts but i didn't manage to do it. Do you know if it is somehow to make ir work?  Maybe there is no need to develop a feature like this?

<img width="755" alt="image" src="https://user-images.githubusercontent.com/69123204/180602879-77bb6e5e-b0c9-4083-a80f-b0a507557c5f.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/69123204/180602899-66fa1363-4531-4f9e-a71a-a7e1cb4d0fc5.png">

**Comment by kyazdani42** [comment]
because they need to implement the recursive dot parsing. You could take a look how it's done in nvimtree or neotree I guess

**Comment by DasGandlaf** [comment]
Is there any news on this?

**Comment by DasGandlaf** [comment]
Sorry, I don't know if this belongs to this issue, but is it possible to set a fallback icon for all `.ts` files? Files ending with `server.ts` do not have the default `.ts` file icon for me, I have to explicitly set the icon for `server.ts` to get it working in my config.

**Comment by alex-courtis** [comment]
> Sorry, I don't know if this belongs to this issue, but is it possible to set a fallback icon for all `.ts` files? Files ending with `server.ts` do not have the default `.ts` file icon for me, I have to explicitly set the icon for `server.ts` to get it working in my config.

Testing with nvim-tree indicates that `bleh.server.ts` `bleh.ts` `server.ts` show the same icon. Which plugin is the problematic one?

**Comment by DasGandlaf** [comment]
Also, If there is f.e. a file called `ControllerTests.java`, is there a possibility to add `Tests.java` to the file icons, and have that previously mentioned file (ControllerTests.java) a different icon? (Notice, that the `Tests.java` does not get preceeded by a `.`
