### ISSUE TITLE
add Vue icon

### ISSUE THREAD

**Issue by ignamartinoli** [kyazdani42/nvim-web-devicons#139]
Add support for Vue icon

**Comment by ignamartinoli** [comment]
This is the `nerd-fonts` icon for **Vue**
﵂

**Comment by kyazdani42** [comment]
please open a PR for it :)

**Comment by ignamartinoli** [comment]
alright, I guess it's time for me to learn to do that ahaha

**Comment by ignamartinoli** [comment]
I see that somebody in the meantime already added it. well, now I know how to PR hehe :)
