### ISSUE TITLE
About default icon.

### ISSUE THREAD

**Issue by glepnir** [kyazdani42/nvim-web-devicons#14]
Hi, Some times we want get an icon that even it doesn't match the ext or name, so use `unknown` replace `default` more better and remove opts? If we dosen't find an icon in icon_data we return `unknown` icon. What do you think?

**Comment by kyazdani42** [comment]
i think there already is a default icon.

**Comment by kyazdani42** [comment]
not sure i understand. You want to specify a specific icon to fallback ?

**Comment by glepnir** [comment]
Don't mind...
