### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by KaloyanStoyanov06** [kyazdani42/nvim-web-devicons#141]

**Comment by KaloyanStoyanov06** [comment]
![image](https://user-images.githubusercontent.com/51166786/176625585-072155a3-df00-4db4-b62f-99ef659ebd82.png)
Items are not showing in neovim

I'm on windows (if that matters)

**Comment by kyazdani42** [comment]
dup of https://github.com/kyazdani42/nvim-web-devicons/issues/76
