### ISSUE TITLE
Can't change C++ icon

### ISSUE THREAD

**Issue by ahmedaljaali** [kyazdani42/nvim-web-devicons#147]
I tried to change C++ icon, but it seems to have two, one for .cc and one for .cpp

**Comment by IZenithy** [comment]
Thank you for responding!, I'm trying to change icon color the code file end with .cc
![2022-07-18_21:29:41](https://user-images.githubusercontent.com/82327047/179578590-243b63f7-53e5-4945-be7f-3e03d39219be.jpg)

**Comment by kyazdani42** [comment]
setup might have been called by a plugin. I'd suggest using the `set_icon` function which takes a table of icons. Otherwise your definiton looks correct.
Something like:
```lua
local my_icons = { ... }
if webdev.has_loaded then
  webdev.set_icon (my_icons)
else
  webdev.setup({ override = my_icons, default = true })
end
```
tell me if this works for you

**Comment by IZenithy** [comment]
Yes, it works, thank you so much.
