### ISSUE TITLE
[Solved] Icons not  work with nerd fonts 

### ISSUE THREAD

**Issue by samicode0** [kyazdani42/nvim-web-devicons#152]
I've installed nvim-web-icons
I've installed a patched font hack font and Fira Code
but nvim-web-devicons don't show icons 
And yes I've make Hack as my default font in Alacritty my default Terminal
I use Arch Linux
![2022-08-24_18-12](https://user-images.githubusercontent.com/53824344/186492496-0a19fbaf-9eb6-4e76-ba9f-e608ffefc607.png)

**Comment by saamuuel** [comment]
I've find how to solve this issue. for people who have same issue install : `ttf-nerd-fonts-symbols` font :)

**Comment by 4539453** [comment]
@samicode0 close issue, if you have solved it.
