### ISSUE TITLE
Add Astro icon

### ISSUE THREAD

**Issue by Je12emy** [kyazdani42/nvim-web-devicons#155]
I'm starting to learn [Astro](https://astro.build/), but I noticed there isn't an icon. Not a dealbreaker tho :D

**Comment by dobbbri** [comment]
add this icon from vscode-material-icon-theme:

https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/main/icons/astro.svg

`
<svg fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M4.428 14.135c-.312.997-.467 1.495-.429 1.968.036.417.178.818.413 1.165.266.392.7.682 1.57 1.261l3.839 2.56c.775.516 1.163.775 1.582.876.37.09.757.09 1.128.003.42-.1.81-.357 1.588-.87L18 18.533c.878-.581 1.318-.87 1.588-1.266A2.43 2.43 0 0 0 20 16.095c.039-.477-.122-.978-.44-1.982l-3.4-10.7c-.165-.52-.247-.779-.405-.972a1.296 1.296 0 0 0-.523-.382c-.23-.092-.502-.092-1.047-.092H9.754c-.547 0-.822 0-1.053.094a1.29 1.29 0 0 0-.524.384c-.158.194-.239.455-.401.977L4.428 14.136zm9.93-9.897c.13.162.198.383.331.82l2.919 9.588a12.146 12.146 0 0 0-3.49-1.18l-1.9-6.423a.248.248 0 0 0-.474 0l-1.878 6.418a12.128 12.128 0 0 0-3.505 1.184l2.934-9.588c.133-.439.2-.658.331-.82.116-.143.267-.254.437-.323.194-.078.423-.078.881-.078h2.095c.458 0 .688 0 .882.078.17.069.32.18.437.324zm-2.263 11.557c1.106 0 2.067-.28 2.548-.692a2.1 2.1 0 0 1-.155 1.636c-.308.57-.755.853-1.158 1.108-.506.321-.941.598-.941 1.34 0 .245.056.479.157.686a1.868 1.868 0 0 1-1.151-1.725v-.046c0-.512.001-1.143-.722-1.143a.765.765 0 0 0-.766.764c-.812-.813-.741-1.983-.741-1.983 0-.239.024-.611.131-.936.302.568 1.44.99 2.798.99z" clip-rule="evenodd" fill="#ff6d00" fill-rule="evenodd" style="stroke-width:.93414"/></svg>
`

**Comment by kyazdani42** [comment]
svg doesn't work in terminals. Emojis are used in patched fonts (see https://www.nerdfonts.com/)

**Comment by camiloaromero23** [comment]
I'm currently using a `chevron_up` as my astro icon. Find it similar enough to not break my head.

``` lua
astro = {
  icon = "",
  color = "#FFFFFF",
  name = "astro",
}
```

**Comment by Je12emy** [comment]
> I'm currently using a `chevron_up` as my astro icon. Find it similar enough to not break my head.
> 
> ```lua
> astro = {
>   icon = "",
>   color = "#FFFFFF",
>   name = "astro",
> }
> ```

Good idea haha
