### ISSUE TITLE
Auto-setup

### ISSUE THREAD

**Issue by romgrk** [kyazdani42/nvim-web-devicons#20]
Have you thought about running `.setup()` automatically? What would you recommend for a plugin that depends on this? Do you have any reasons not to run `.setup()` automatically? If I may argue, anyone that has the plugin in their config is very highly to want `.setup()` to be called.

Reference: https://github.com/romgrk/barbar.nvim/issues/11

**Comment by kyazdani42** [comment]
you can call `has_loaded` to make sure setup wasn't already called.

**Comment by romgrk** [comment]
Q1: Can't you call `.setup()` yourself automatically? Why is it left to the user/plugin author to do it?
Q2: If you insist on someone else than you calling it, why don't you make `.setup()` return if it has already been called rather than push the `.has_loaded()` logic to users?

**Comment by akinsho** [comment]
Lua plugins exposing a `setup` function call that a user then uses doesn't seem very unusual, tbh a lot of vim plugins require the user to manually actually activate the plugin. Also calling setup automatically makes a lot of assumptions about what the intended usage for this plugin, since this plugin might be used as a dependency for another one the plugin author might not want this.

**Comment by kyazdani42** [comment]
also users could call setup themselves to provide for alternative config

**Comment by kyazdani42** [comment]
but maybe has loaded should be done inside setup

**Comment by romgrk** [comment]
Counter-arguments:

 - Isn't adding `Plug 'kyazdani42/nvim-web-devicons'` the usual mark that the user does want to use the plugin? I know many lua plugins expose a `.setup()` function but it doesn't mean that it's a good thing to do so. Also there is no configuration to do for this plugin.

 - I challenge you to produce a use-case where the user did add the plugin to their vimrc BUT does not want the plugin `.setup()` to be run automatically.

> since this plugin might be used as a dependency for another one the plugin author might not want this

 - If the `.setup()` function is called from `plugin/nvim-web-devicons.vim` there is nothing to worry about

> also users could call setup themselves to provide for alternative config

 - I'm not sure that I understand. This plugin doesn't seem configurable, is it?

**Comment by kyazdani42** [comment]
lazy loading maybe...?

**Comment by kyazdani42** [comment]
the setup fonction allows to override icons and colors

**Comment by romgrk** [comment]
> lazy loading maybe...?

Lazy-loading sounds good. I've updated #22.
