### ISSUE TITLE
Missing highlights with recent version

### ISSUE THREAD

**Issue by elianiva** [kyazdani42/nvim-web-devicons#24]
The highlights seems to be missing with recent version. I've tried several recent versions starting from [56817c27](https://github.com/kyazdani42/nvim-web-devicons/commit/56817c27b4245c2b6c067a7413a69d0fd27a2770) until [23a9fbb6](https://github.com/kyazdani42/nvim-web-devicons/commit/23a9fbb6de546a4cb2e7d2fe2ff4e09e99b5fd2e) and it seems like starting from [e7667ae](https://github.com/kyazdani42/nvim-web-devicons/commit/e7667ae4816c76518fc6299f4773a85dc251b6ea) the highlighting doesn't work.

![Group 55](https://user-images.githubusercontent.com/51877647/97525686-f7beb400-19d9-11eb-98c4-351c4f3ea391.png)

**Comment by glepnir** [comment]
Because your colorscheme has this setting `hi clear` and load after nvim-web-devicons. check with `hi DevIconLua`, the value will be `cleared`.  Can you try to load your colorscheme before load nvim-web-devions? I think it will be solved.

**Comment by elianiva** [comment]
> Because your colorscheme has this setting `hi clear` and load after nvim-web-devicons. check with `hi DevIconLua`, the value will be `cleared`. Can you try to load your colorscheme before load nvim-web-devions? I think it will be solved.

Yup. It is indeed solved. Thanks!
