### ISSUE TITLE
devicons highlight is no longer re-applied if re-sourcing init.vim

### ISSUE THREAD

**Issue by akinsho** [kyazdani42/nvim-web-devicons#25]
@kyazdani42 since #22 was merged and `setup()` is now only allowed to be called once, if you try and source your init.vim during an editing setting the highlights are no longer re-applied. I was solving this issue in `nvim-bufferline` by using an `autocmd ColorScheme * lua.require'nvim-devicons'.setup()` to re-apply the highlights since most colorschemes will clear the existing highlights if you re source your `init.vim` I think calling `setup` is now not possible more than once so you can't re-apply the highlights.

I think a solution could be adding the autocommand to the plugin directly? What are your thoughts? if you agree I can test if it works and make a PR later today?

**Comment by akinsho** [comment]
alternatively we can remove the `if loaded then return` block since we don't need to prevent it being called twice.

**Comment by romgrk** [comment]
Encountered the same issue, I also agree that it needs to be callable multiple times.
