### ISSUE TITLE
lua/nvim-web-devicons.lua:855: attempt to call field ' cmd' (a nil value)

### ISSUE THREAD

**Issue by romgrk** [kyazdani42/nvim-web-devicons#30]
Reference: https://github.com/romgrk/barbar.nvim/issues/32

**Comment by obaranek** [comment]
output of print(lua require'nvim-web-devicons'.setup())
E488: Trailing characters

**Comment by romgrk** [comment]
Not, I mean add a line like `print(hl_group)` just before [this one](https://github.com/kyazdani42/nvim-web-devicons/blob/master/lua/nvim-web-devicons.lua#L855).

**Comment by kyazdani42** [comment]
vim version not up to date

**Comment by kyazdani42** [comment]
lua plugins run on nvim 5.x not 4

**Comment by obaranek** [comment]
this is the output: DevIconDiff

**Comment by kyazdani42** [comment]
please update to neovim nightly. what is your current nvim version ? (`nvim --version`)

**Comment by obaranek** [comment]
NVIM v0.4.4

**Comment by kyazdani42** [comment]
this plugin works with neovim 0.5.x, please upgrade to neovim nightly.

**Comment by kyazdani42** [comment]
well actually i might consider making it available to neovim 0.4.x

**Comment by obaranek** [comment]
the latest neovim version on ubuntu PPA is 0.4.x

**Comment by obaranek** [comment]
it works now! thank you!

**Comment by kyazdani42** [comment]
0.4.x is stable. if you wan't to update to nightly you can still build from source, it's not hard :) good luck

**Comment by obaranek** [comment]
Updating neovim solved the issue, thanks!
