### ISSUE TITLE
How to change default global icon?

### ISSUE THREAD

**Issue by tami5** [kyazdani42/nvim-web-devicons#32]
Hey @kyazdani42 , thanks so much for this port. 

I'd like to change `default_icon` to something else

I tried 
```lua
require'nvim-web-devicons'.setup {
 override = {
   default_icon = {
     icon = " ",
     color = "#6d8086",
     name = "Default",
    }
  };
}
```
But didn't work for me

Thanks again

**Comment by kyazdani42** [comment]
hello!
it seems that overriding the default is not possible, ill push some code to enable overriding it :)

**Comment by tami5** [comment]
Thanks so much @kyazdani42 !!
