### ISSUE TITLE
overriding icons of filetypes dont work 

### ISSUE THREAD

**Issue by siduck76** [kyazdani42/nvim-web-devicons#45]
Ive migrated to init.lua to init.vim now , but the overriding of icons on filetypes doesnt work 
 here's my config : 

![image](https://user-images.githubusercontent.com/59060246/110238896-0e69ae80-7f6a-11eb-931e-a657258efd21.png)
 

![image](https://user-images.githubusercontent.com/59060246/110238863-df533d00-7f69-11eb-9ea9-3c741d7d707c.png)

**Comment by kyazdani42** [comment]
you might need to load this before other plugins

**Comment by siduck76** [comment]
I already did but no luck

**Comment by kyazdani42** [comment]
what package manager do you use ? I just tried it and it works fine

**Comment by siduck76** [comment]
packer.nvim . I recently migrated to init.lua and the same config was working with my old init.vim

**Comment by kyazdani42** [comment]
i use packer too, under the `config` key it works just fine for me. You might have plugin loading issues. Do you lazy load plugins ?

**Comment by siduck76** [comment]
lazy load plugins? whats that? I loaded the plugin above all 
![image](https://user-images.githubusercontent.com/59060246/110268514-c4271280-7fe7-11eb-8842-e0629a62e708.png)

my init.lua also loads this plugin first 
![image](https://user-images.githubusercontent.com/59060246/110268754-3d266a00-7fe8-11eb-8480-55de9ea07676.png) 

my nvim-web-devicons config in (~/.config/nvim/lua/nvim-web-devicons/lua.lua)

![image](https://user-images.githubusercontent.com/59060246/110268797-4e6f7680-7fe8-11eb-85f4-25f972c3d955.png)

**Comment by siduck76** [comment]
Nvm this is fixed now , I forgot to add the vim.cmd [[packadd nvim-web-devicons]] in my web-devicons conf .
