### ISSUE TITLE
Tex icon affects following text (if not separated by a space)

### ISSUE THREAD

**Issue by mrossinek** [kyazdani42/nvim-web-devicons#46]
I would like to point out an issue which I encountered a few months ago and had raised in `vim-dirvish`. A few weeks ago I added some updates which lead me to believe that this is indeed an issue of `nvim-web-devicons` rather than `vim-dirvish`.
Rather than duplicating everything, please refer to the last updates in this issue: https://github.com/justinmk/vim-dirvish/issues/204

**Comment by mrossinek** [comment]
I realize that the information should really also be here for documentation purposes. Thus, here is the example to reproduce the issue:

Try for example opening the following file:
```
Text before TeX character:
test ﭨ

Text after TeX character (with a separating space):
ﭨ test

Text after TeX character (withOUT a separating space):
ﭨtest
```

Here is a screenshot of the results:
![screenshot_1614188843](https://user-images.githubusercontent.com/21973473/109042661-beb8f680-76d0-11eb-81aa-a0f072b24866.png)


The editors are:
* Top left: `nvim test.tex`
* Bottom left: `nvim --noplugin --clean test.tex`
* Top right: `\vim test.tex`
* Bottom right: `\vim --noplugin --clean test.tex`

System: `Linux 5.10.16-arch1-1`
Neovim: `NVIM v0.5.0-dev+1094-gd623400ca`
Vim: `VIM - Vi IMproved 8.2; Included patches: 1-2489`

**Comment by kyazdani42** [comment]
Hi again,
i can say again that the issue does not come from this plugin. Try using [this](https://github.com/kyazdani42/nvim-tree.lua) and you'll see how the text icon and following text renders properly. 
I'm not sure what's the issue in your screenshot which shows 4 perfectly similar buffers :/

**Comment by mrossinek** [comment]
Hi! Thanks for the reply. I will check out your other project! Might be a while before I get to it thought as I am rather busy lately.
I also just noticed the same issue as above for the `svg` icon... I was wondering whether it may be some "reverse text unicode char" which gets triggered when not properly considering the icon as double width. But I really am no expert on this...

**Comment by kyazdani42** [comment]
unicode characters can be 2, 3 or 4 bytes long, usually you should print out the correct number of bytes or else it might do some unusual things. But vim/nvim should handle that by itself properly (it's just utf-8 after all), not sure if dirvish does some funky stuff with the output ^^

**Comment by mrossinek** [comment]
But since the examples I posted above reproduce the issue in plain vim/nvim, should I rather raise the issue there?
That is completely independent of the dirvish..

**Comment by kyazdani42** [comment]
I cannot reproduce this issue on linux, neovim latest build. Which neovim version do you have ?

**Comment by mrossinek** [comment]
I just did a fresh compilation and installation of Neovim's master branch. Copying the contents of the example in my first comment on this issue still produces the same problem.
Here is the output of `:version`:
```
:version
NVIM v0.5.0-dev+1174-g9f5c8226b
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D
MIN_LOG_LEVEL=1 -I/home/max/Installations/neovim/build/config -I/home/max/Installations/neovim/src -I/home/max/Installations/neovim/.deps/usr/include -I/usr/include -I/home/max/Installations/neovim/build/src/nvim/auto -I/home/max/Installations/neovim/build/include
Compiled by max@ArchThinkPad

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/max/.local/share/nvim"

Run :checkhealth for more info
```

**Comment by mrossinek** [comment]
I think the problem lies with my terminal emulator `kitty`...
I am sorry for not having investigated this earlier. I just installed `alacritty` and it does not suffer from this issue. I will take my issue to `kitty` then :+1: 

Sorry for the spamming and re-raising of this issue

**Comment by jdrouhard** [comment]
@kyazdani42 I did some investigation on this.

I don't think the problem is with terminal emulators. The issue is that some of the icons switch the active direction of text to RTL and affects the surrounding text. Unicode introduced [direction isolates](https://en.wikipedia.org/wiki/Bidirectional_text#Isolates) specifically to help with this issue.

I've verified that if the icon text is surrounded with LTR isolate markers, then the icons will no longer mess up the rendering of surrounding text if the terminal emulator properly applies the bidi algorithm (modern terminal emulators do). Isolates specifically _do not affect the direction of the surrounding text_ so this won't affect rendering if the icon appears in RTL text.

Maybe the icons that use codepoints that are designated as RTL (Tex, SVG, etc) should have LTR isolate markers around the unicode codepoint. This would involve something like:

```lua
["tex"] = {
    icon = "<U+2066>ﭨ<U+2069>", -- actual utf-8 encoded codepoints instead, this is for demonstration
    color = "#3D6117",
    name = "Tex"
  };
...
```

Would you like me to open a new issue for this? What do you think?
