### ISSUE TITLE
Feature request: xterm-256 color support using converter?

### ISSUE THREAD

**Issue by CallumHoward** [kyazdani42/nvim-web-devicons#49]
Hi, my favorite terminal emulator doesn't support true colors yet :'(

Would it be possible to use something like this snippet: https://gist.github.com/jasonbradley/4357406
to convert hex to rgb and provide xterm-256 colors?

**Comment by kyazdani42** [comment]
Hi, of course 256 should be supported. go make a PR i think it would not be too hard to do

**Comment by CallumHoward** [comment]
I switched to Kitty which does support true colours now, feel free to close this
