### ISSUE TITLE
How to override icons that start with a dot?

### ISSUE THREAD

**Issue by hrqmonteiro** [kyazdani42/nvim-web-devicons#52]
```
require'nvim-web-devicons'.setup {
    -- your personnal icons can go here (to override)
    -- DevIcon will be appended to `name`
    override = {
        lua = {icon = "", color = colors.nord15, name = "lua"},
        .gitignore = {icon = "", color = colors.nord4, name = "GitIgnore"},
    },
    -- globally enable default icons (default to false)
    -- will get overriden by `get_icons` option
    default = true
}
```

This gives an error.

How do i properly override the `.gitignore` icons? (And others that start with a dot)

**Comment by akinsho** [comment]
@hrqmonteiro you need to but `.gitignore` in quotes like `['.gitigore']` non alphabetical keys in lua need to be put in braces and quoted

**Comment by hrqmonteiro** [comment]
> @hrqmonteiro you need to put `.gitignore` in quotes like `['.gitigore']` non alphabetical keys in lua need to be put in braces and quoted

Thanks, man!
