### ISSUE TITLE
Wrong devicon when .vimrc/.zshrc opened from startify screen

### ISSUE THREAD

**Issue by reportaman** [kyazdani42/nvim-web-devicons#58]
The devicons for files like ``.vimrc``, ``.zshrc`` is incorrect when file is opened from [vim-startify](https://github.com/mhinz/vim-startify) screen. The icons are correct if these files are opened directly using commands like ``:e .vimrc<CR>``/ ``:e.zshrc<CR>``. The same problem does not occur for most of the other file types (including files that end in ``.vim``).

Steps to recreate:

1. Install [vim-startify](https://github.com/mhinz/vim-startify)
2. Reopen nvim
3. Open ``.vimrc`` file using usual command ``:e .vimrc<CR>``.
4. Close, and reopen nvim
5. Open ``.vimrc`` file by pressing ``<CR>`` on ``.vimrc`` file in the MRU buffer list of [vim-startify](https://github.com/mhinz/vim-startify)'s startup screen.

**Comment by kyazdani42** [comment]
are your sure this issue is realted to nvim-web-devicon and not vim-startify ? This plugin only provide a simple function, the rest is left to the plugin developers to implement.

**Comment by reportaman** [comment]
@kyazdani42 I would think more a ivim-web-devicon question. vim-startify developer could argue its just a start-screen that can be used to open MRU or other important files. What can he do wrong in opening files? If there is an interest in fixing this then one of you will have to decide to debug a bit. @mhinz, any opinion? I think it is worthwhile as vim-startify & nvim-web-devicons are a good combination, and each worth using in its own right.

**Comment by kyazdani42** [comment]
waiting for @mhinz before going on further investigation, i'm not sure why most plugins would work as expected using this lib but not vim-startify ? If this issue comes from nvim-web-devicon, i will fix it.

**Comment by mhinz** [comment]
By default, startify isn't using nvim-web-devicons. Following the steps above, I see nothing happening in startify.

**Comment by kyazdani42** [comment]
if vim-startify doesn't use nvim-web-devicons, how is this issue relevant ?

**Comment by kyazdani42** [comment]
i think it's because you initialize nvim-web-devicons after bufferline which already have initialized it. Try to put your nvim-web-devicon setup before all other plugins initializations if you want changes to take effect properly.

**Comment by reportaman** [comment]
@kyazdani42 I tried couple of refactorings, it didn't change anything. Can you please check if/how these lines need to be rearranged? Please post it too...

**Comment by kyazdani42** [comment]
after looking at the video you sent, i'm completely sure this issue should be addressed to bufferline. I'm closing this because it's out of the scope of this library.

**Comment by kyazdani42** [comment]
PS: feel free to reference your issue to this one
