### ISSUE TITLE
File Icons does not work for nvimTree

### ISSUE THREAD

**Issue by ashkan117** [kyazdani42/nvim-web-devicons#60]
As the title states. My file icons works for telescope and bufferline but not nvimTree.

Example that it does not work for nvimTree but does work for bufferline
![image](https://user-images.githubusercontent.com/30095041/117730958-20eaa900-b1a2-11eb-949c-f8bb142d979b.png)

Example that shows it works for telescope
![image](https://user-images.githubusercontent.com/30095041/117730975-26e08a00-b1a2-11eb-816a-bf840a9151e4.png)

**Comment by kyazdani42** [comment]
works fine on my end, could you try to `set debug=throw` and reopen nvim ? maybe you have an issue with your configs. Also could you provide me with a minimal init file that i could use to reproduce this issue please ?

**Comment by ashkan117** [comment]
I'm new to debugging neovim. I set debug=throw and after restarting nvim nothing changes.

I added a link to my dot files
https://github.com/ashkan117/dotfiles/tree/master/neovim-lua

**Comment by kyazdani42** [comment]
@ashkan117 your repository seems private, i cannot access the configuration provided

**Comment by ashkan117** [comment]
@kyazdani42 I believe it should be public now. Sorry about that.

**Comment by ashkan117** [comment]
For whatever reason I had vim.cmd [[packadd nvim-tree.lua]] in my config. Commenting this out resolved my issue

**Comment by Iron-E** [comment]
It seems there's some issue with `nvim-tree.lua` being lazy-loaded as an `opt` plugin. With `packer.nvim` and the following spec:

```lua
use {'kyazdani42/nvim-tree.lua', after='nvim-web-devicons'}
```

The plugin reproduces this behavior. However, removing the `after=` causes the bug to go away. `:packadd`ing `nvim-tree.lua` must cause some sort of issue, over Neovim letting it `start` automatically.

**Comment by kyazdani42** [comment]
because nvim-tree doesn't use a classic lua setup which makes lazy loading fail on some cases. I must do a refactoring but it is quite big and it will take some time :)

**Comment by Iron-E** [comment]
Thank you for your dedication!

Should this issue be reopened for the meantime?

**Comment by kyazdani42** [comment]
there are many issues related to lazy loading i believe, no need to add another one :)

**Comment by SnakeHit** [comment]
Thank you all, This solve my Problem.
