### ISSUE TITLE
The icon for directory does not show up.

### ISSUE THREAD

**Issue by thuan-gempage** [kyazdani42/nvim-web-devicons#65]
Hi,
As the title said, the icon for any directory does not display. I tried by overriding in the setup.
![image](https://user-images.githubusercontent.com/73817171/124360197-b4949f00-dc52-11eb-86a7-90295acf7da0.png)
The icon for the `test.js` file is displayed as expected, however, the icon for  other two dirs are not work.
Thank you!

**Comment by xiyaowong** [comment]
how do you call get_icon

You should make sure that one of the first or second arguments is equal to the key

**Comment by thuan-gempage** [comment]
I found the problem, the `nvim-tree.lua` plugin does not render the icon for the directory.

**Comment by kyazdani42** [comment]
closing this issue since nvim-tree has a documentation on how to change the icon for directories.
