### ISSUE TITLE
How to override multiple filetypes?

### ISSUE THREAD

**Issue by zeitchef** [kyazdani42/nvim-web-devicons#66]
I'm trying to override both `gitignore` and `gitconfig` file icons. My current config looks like this:

```
git = {
    icon = '<icon>',
    color = '#e06c75',
    name = 'gitignore'
},
```
This works fine, but when I do something like `name = ['gitconfig', 'gitignore']` or `name = {'gitconfig', 'gitignore'}` it doesn't work. Grateful for any tips on how to do this!

**Comment by zeitchef** [comment]
Ok, so it seems I was thinking about this all wrong. Here's how I got this to work:

```
['.gitconfig'] = {
    icon = '<icon>',
    color = '#e0cc75',
    name = 'gitconfig'
}

['.gitignore'] = {
    icon = '<icon>',
    color = '#e0cc75',
    name = 'gitignore'
}
```

Not sure if this is the exact right approach, but it's what worked for me :)

**Comment by kyazdani42** [comment]
this is the right approach, the plugin setup is quite basic :)
