### ISSUE TITLE
Icons are incorrectly labeled

### ISSUE THREAD

**Issue by ex4722** [kyazdani42/nvim-web-devicons#70]
Not sure what happened but it seems that the icons are named incorrectly. For example under the python label their seems to be a database icon and under the c label their is a icon that says npm. These files are from a direct git clone so I think these are the latest version.

![image](https://user-images.githubusercontent.com/77011982/128792132-c8952a62-31a1-41f0-bec0-b123325de429.png)
![image](https://user-images.githubusercontent.com/77011982/128792150-ae9eade6-919b-4436-a0d6-8edf60f5bf6b.png)

**Comment by kyazdani42** [comment]
closing this because your font must be badly configured, please install a font that support the icons properly. It renders as expected in most people's terminal and so does it in mine :)
I can help you though, with some infos, i'd need:
1 - which terminal are you using
2 - which system are your running

**Comment by ex4722** [comment]
Thanks for the help and sorry for posting this in the wrong place. I am currently running arco linux and my terminal is alacritty.

**Comment by kyazdani42** [comment]
you might have a wrong font configuration, try reading [this](https://wiki.archlinux.org/title/Font_configuration) or install a [patched font](https://www.nerdfonts.com/).
If the issue still persist, you might have a font installed on your system that takes precedence over others, which might lead to unexpected results. Good luck :)

**Comment by ex4722** [comment]
Thank you for your time and hard work. Turns out installing a couple of fonts did the trick. I installed 3 different fonts and the it worked now works.
