### ISSUE TITLE
icon for org

### ISSUE THREAD

**Issue by ashincoder** [kyazdani42/nvim-web-devicons#71]
The org icon is normally a unicorn. Have u ever come across it. If yes please add it. I have searched my pants of and I couldn't find it.

**Comment by kyazdani42** [comment]
I'm really not sure where to find this if it's not present in [this](https://www.nerdfonts.com/cheat-sheet) page, I don't think it would be available yet but maybe you can find a replacement for it

**Comment by ashincoder** [comment]
![2021-08-14-061246_87x95_scrot](https://user-images.githubusercontent.com/83629316/129429473-80c67897-080b-4d13-82d8-771e92c8d70b.png)
My only corncern is how can this be here. this is doom-modeline https://github.com/seagle0128/doom-modeline

**Comment by kyazdani42** [comment]
doom is an emacs config which is renderer in a GUI, not a TUI, so they can render svg and such i believe which we cannot do.

**Comment by ashincoder** [comment]
Mm. I see. Yeah that makes sense.

**Comment by ashincoder** [comment]
Should I close this issue ?? What do u say ??

**Comment by kyazdani42** [comment]
closing this for you. If you find the icon at some point you could make a PR to include it

**Comment by ashincoder** [comment]
ok
