### ISSUE TITLE
help for install and using this plugin on windows

### ISSUE THREAD

**Issue by grimgort** [kyazdani42/nvim-web-devicons#76]
hello,
I don't understand how to have the icons in neovim on a windows computer. I can't find how to do it on the internet... If anyone can help me it would be great
thanks
![image](https://user-images.githubusercontent.com/44238325/132037357-98593865-3194-49b8-89bc-48aa4ebcf38f.png)

**Comment by Zamachi** [comment]
I am on Windows 10 as well, and I have the same issue as you do...
Namely I've tried both this, and vim-devicons, the same symbols(altho probably even more) are missing, or "unrecognized", don't know how to phrase it...

I'm using Fira Code nerd font, and from what I got on the Nerd font Github, on Windows 10 it's to be installed with (if using a package manager): `choco install firacode`, and indeed it installs it, I can apply it in my init.vim with `set guifont=Fira\ Code:h10`, but the missing symbols still do not appear...
Also, symbols that *do* appear, are usually cut in half, either horizontally/vertically, I don't know why, can't find any issues related to it...

**Comment by grimgort** [comment]
I managed to make it work by executing the ps1 script of the nerf-font repository and by chagnat the font in neovim
![image](https://user-images.githubusercontent.com/44238325/132176763-fb2360cf-8823-4912-ae28-e5e2a0775779.png)

**Comment by pietromesadri** [comment]
Hi,
To fix this issue:
1. go to [Nerd Fonts](https://www.nerdfonts.com/) and choose a font, you can also patch an existing font.

2. After you download said font go to your windows font settings and install the files from you zip file (you can do it by dragging and dropping them into the font settings window.

![image](https://user-images.githubusercontent.com/23194328/146913359-07341b81-4d05-4cf1-87a1-c83b27e7e44e.png)

3. If you use it through the Windows Terminal or another one, go to the settings and change to your nerd font.

![image](https://user-images.githubusercontent.com/23194328/146913743-c26cda34-39c8-4cf1-b6ab-d1aeab6c3177.png)

You can launch the qt version (the windowed version) through the terminal and it will apply the new font. Or you can also the font in your init.vim file.

**Comment by bertin0** [comment]
> Hi, To fix this issue:
> 
>     1. go to [Nerd Fonts](https://www.nerdfonts.com/) and choose a font, you can also patch an existing font.
> 
>     2. After you download said font go to your windows font settings and install the files from you zip file (you can do it by dragging and dropping them into the font settings window.
> 
> 
> ![image](https://user-images.githubusercontent.com/23194328/146913359-07341b81-4d05-4cf1-87a1-c83b27e7e44e.png)
> 
>     3. If you use it through the Windows Terminal or another one, go to the settings and change to your nerd font.
> 
> 
> ![image](https://user-images.githubusercontent.com/23194328/146913743-c26cda34-39c8-4cf1-b6ab-d1aeab6c3177.png)
> 
> You can launch the qt version (the windowed version) through the terminal and it will apply the new font. Or you can also the font in your init.vim file.

I have done this with FIra Code and I still have no icons. Any idea why?

**Comment by grimgort** [comment]
thanks. it s work
