### ISSUE TITLE
bug: Unable to override/add icons after the latest commit

### ISSUE THREAD

**Issue by dhruvmanila** [kyazdani42/nvim-web-devicons#78]
The solution in the latest commit (1a94ff06dfb0a2240f447dd2e351010725b6fd64) does not seem to be good as that will not allow anyone to add/override an icon.

I have [`yamatsum/nvim-nonicons`](https://github.com/yamatsum/nvim-nonicons) installed which overrides some of the icons from `nvim-web-devicons`, which is successful because it calls the `setup` function first. Then, I also have my own setup which adds custom icons (which now fails) and then there's [`tamago324/lir.nvim`](https://github.com/tamago324/lir.nvim) which adds its own folder icon (which also fails).

A solution would be to expose an `override` function which would allow anyone to add/override an icon without doing the `setup` call.

**Comment by Pocco81** [comment]
I second this. Latest commit seems to have broken this...
