### ISSUE TITLE
Use filetype instead of extension

### ISSUE THREAD

**Issue by hkupty** [kyazdani42/nvim-web-devicons#8]
Hi! First of all, thanks for the nice plugin.

Some syntaxes could have multiple extensions associated, for example (yaml,yml), (clj,cljc,cljs,edn), (c, h), (markdown, md) and so on, while some files might also not have the extension but force a filetype by modeline, for example, so instead of having an entry for each extension, maybe it's better to rely on `ft`. WDYT?

**Comment by kyazdani42** [comment]
that's a good suggestion. Although it would probably slow down the plugin, because the filetype is given for a buffer and not for a file. I don't know if there is an existing vim function to get the filetype of a file.

**Comment by hkupty** [comment]
:thinking: Maybe we can have a mapping from extension to `ft` for those cases. My usecase is to have the icon+highlight in the statusbar, so it's easier if I use the - already available - filetype. :)

**Comment by akinsho** [comment]
@hkupty I currently use this in my statusline with
```
let extension = fnamemodify(bufname(), ':e')
```
To pass the extension in to the `get_icon` function. If that helps 🤷🏿‍♂️ .

**Comment by hkupty** [comment]
I use something similar for now:
```lua
          local extension = string.match(buffer.name:reverse(), "^(%a+)"):reverse()
          local ok, icon, hl = pcall(require("nvim-web-devicons").get_icon, buffer.name, extension)
```

The thing is, some files like bash scripts don't have extensions, so. Also, you can manually force a filetype with a modeline, so I guess it'd be more resilient if relying on the filetype instead.

**Comment by kyazdani42** [comment]
this would slow down the whole process... i think most plugins use this small library to enhance the ui of their file display, which in most case, requires a good performance. Adding a layer for the filetype would probably make those plugin authors not really happy. You can map you filetypes on files withouth an extension to return an extension for your statusbar, and fall back to the file extension otherwise, which would help displaying the right icon !
like so:
```lua
local mapFtToExt = { sh = "sh", python = "py" }
local filetype = api.nvim_buf_get_option(0, "ft")
let extension = fnamemodify(bufname(), ':e')
require"nvim-web-devicons".get_icon(buffer.name, mapFtToExt[filetype] or extension)
```

**Comment by kyazdani42** [comment]
or we could add definitions and you could pass `extension or filetype` to the extension param.

**Comment by hkupty** [comment]
Seems fair. I've actually encounter another compelling reason to map filetype and extension (when limiting search to files of the same file type), so I've created [a separate plugin for this](https://github.com/hkupty/classifier.nvim).

I guess this can be considered solved then. Thanks for the consideration nonetheless.

Best regards,

**Comment by qubidt** [comment]
@hkupty fyi

```lua
string.match(buffer.name:reverse(), "^(%a+)"):reverse()
```

should be 

```lua
string.match(buffer.name:reverse(), "^([^./]+)"):reverse()
```

so it'll catch extensions that have numbers :)

**Comment by hkupty** [comment]
Thanks for the heads up. That didn't cross my mind.

**Comment by qubidt** [comment]
deleted my comment on accident, but it said:

```lua
string.match(buffer.name:reverse(), "^(%a+)"):reverse()
```

should be

```lua
string.match(buffer.name:reverse(), "^([^./]+)"):reverse()
```

or it'll break on extensions with numbers

this is also equivalent:

```lua
string.match(vim.api.nvim_buf_get_name(0), "^.+[./](.+)$")
```

of course `vim.fn.expand("%:e")` is easier than all of that, lol
