### ISSUE TITLE
Support for overrided icons

### ISSUE THREAD

**Issue by adelarsq** [kyazdani42/nvim-web-devicons#9]
Hello,

Is it possible to override the icons from this plugin?

I'm the creator from the [adelarsq/vim-emoji-icon-theme](https://github.com/adelarsq/vim-emoji-icon-theme) plugin, that extends [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons) (and some others) to use emojis instead of overrided fonts. My idea is also to support this plugin.

**Comment by kyazdani42** [comment]
not yet, you could make a PR to extend the setup function to take a table that would override fields in the icons table.

**Comment by adelarsq** [comment]
Thanks @kyazdani42. I added on my TODOs to create a PR for this.

**Comment by adelarsq** [comment]
Now its possible to use this plugin together with [vim-emoji-icon-theme](https://github.com/adelarsq/vim-emoji-icon-theme) to a nice look with emojis instead of custom fonts 🤗🎉
