### ISSUE TITLE
I can't get colors to work

### ISSUE THREAD

**Issue by Hubro** [kyazdani42/nvim-web-devicons#92]
I can't get colors to work in nvim-tree or telescope. I have been troubleshooting this problem on and off for months. I am at my wits end, I give up. I'm dumping my config folder here in case you feel like figuring out what's breaking icon colors.

In short, my nvim-tree config looks like this:

```
require("nvim-web-devicons").setup{ default = true }

require("nvim-tree").setup {
  hijack_cursor = true,
  view = {
    width = 40
  }
}
```

Result:

![image](https://user-images.githubusercontent.com/597206/137521289-dfc18db8-f394-4688-bfe9-0b5fc7f3a6c6.png)

Frustratingly, if I reload my plugin config (`:so %`) and open nvim-tree again, it now has colored icons, but telescope doesn't:

![image](https://user-images.githubusercontent.com/597206/137521367-47d4e4af-396f-4e67-9346-1627cfd0ca42.png)

I have spent more hours troubleshooting this than I care to admit, shuffling things around, disabling various plugins, configuring plugins in different orders etc. If you have any suggestions for what else I can try, I'd appreciate it a lot.

Here is my nvim config: [nvim-config.zip](https://github.com/kyazdani42/nvim-web-devicons/files/7354715/nvim-config.zip)

**Comment by kyazdani42** [comment]
hi !
Did you manage to reproduce with a smaller configuration ? your configuration is quite big.
Also which version of neovim do you use ? and which terminal do your run neovim in ?

**Comment by Hubro** [comment]
Also I just realized, when I reload my config I don't get full color support in nvim-tree, only the git status icons get colors. The file type icons are still white :thinking:

**Comment by Hubro** [comment]
@kyazdani42 I finally found the issue. My colorscheme setup code waits until the first BufEnter, because of a bug I ran into when setting the colorscheme before a client had connected. If I comment out those lines, I get colored icons. Here is a minimal setup demonstrating the problem:

```lua

set termguicolors

exec plug#begin('./bundle')

Plug 'ryanoasis/vim-devicons'
Plug 'kyazdani42/nvim-web-devicons'
Plug 'kyazdani42/nvim-tree.lua'

Plug 'morhetz/gruvbox'

exec plug#end()

lua <<LUA
require("nvim-web-devicons").setup{ default = true }
require("nvim-tree").setup{}
LUA

au BufEnter * ++once colorscheme gruvbox
```

**Comment by kyazdani42** [comment]
did you try fixing the colorscheme issue instead ? you should just be able to run colorscheme during startup.

**Comment by Hubro** [comment]
Setting the colorscheme normally works for now.

I don't quite remember exactly what forced me to delay setting the colorscheme in the first place. I think I was playing with a GUI for Neovim.
