### ISSUE TITLE
Add icon for solidity

### ISSUE THREAD

**Issue by UltiRequiem** [kyazdani42/nvim-web-devicons#99]
https://soliditylang.org/
extension: ".sol"

**Comment by evantancy** [comment]
pls ser may we have solidity icon

**Comment by kyazdani42** [comment]
open a PR if the icon exists in a font. I don't think there is one at the moment. 
See https://www.nerdfonts.com/cheat-sheet

**Comment by evantancy** [comment]
the closest thing to it is the eth icon from the linked website, with the name or class idk `nf-mdi-currency_eth`. i believe it's the same one that [vim-devicons#396](https://github.com/ryanoasis/vim-devicons/pull/396) uses
